const SVG_NS="http://www.w3.org/2000/svg";
function el(name,attrs={}){const node=document.createElementNS(SVG_NS,name);for(const [key,value] of Object.entries(attrs))node.setAttribute(key,String(value));return node;}
function groupSvg(viewBox="0 0 120 48"){const svg=el("svg",{viewBox,"aria-hidden":"true",focusable:"false"});svg.classList.add("insignia-svg");return svg;}
function addWing(svg,side){const g=el("g",{transform:side==="left"?"":"translate(120 0) scale(-1 1)"});const path=el("path",{d:"M8 27 C22 14 36 12 52 17 C40 19 31 24 23 32 C35 28 44 27 52 28 C40 34 28 37 12 35 Z",fill:"currentColor"});g.append(path);svg.append(g);}
function badgeParachutist(){const svg=groupSvg();addWing(svg,"left");addWing(svg,"right");svg.append(el("path",{d:"M60 6 C49 6 42 13 42 20 H78 C78 13 71 6 60 6 Z",fill:"none",stroke:"currentColor","stroke-width":"3"}),el("path",{d:"M45 20 L57 36 M75 20 L63 36 M60 20 V37",stroke:"currentColor","stroke-width":"2",fill:"none"}),el("path",{d:"M54 37 H66 L63 42 H57 Z",fill:"currentColor"}));return svg;}
function rifleWreath(combat=false){const svg=groupSvg();svg.append(el("path",{d:"M29 36 C16 29 15 15 28 9 M91 36 C104 29 105 15 92 9",stroke:"currentColor","stroke-width":"4",fill:"none","stroke-linecap":"round"}),el("path",{d:"M37 30 L83 16 M39 16 L81 30",stroke:"currentColor","stroke-width":"4","stroke-linecap":"round"}));if(combat)svg.append(el("rect",{x:44,y:8,width:32,height:8,rx:2,fill:"currentColor"}));return svg;}
function badgeAirAssault(){const svg=groupSvg();addWing(svg,"left");addWing(svg,"right");svg.append(el("path",{d:"M58 9 H64 L66 20 L75 25 L72 29 L64 26 L62 39 H58 L56 26 L48 29 L45 25 L54 20 Z",fill:"currentColor"}));return svg;}
function qualificationBadge(result="marksman",clasp="RIFLE"){const svg=groupSvg("0 0 120 70");const shape=result==="expert"?"M60 6 L76 18 L70 40 H50 L44 18 Z":result==="sharpshooter"?"M60 6 L77 19 L70 39 H50 L43 19 Z":"M60 7 L73 18 L68 38 H52 L47 18 Z";svg.append(el("path",{d:shape,fill:"none",stroke:"currentColor","stroke-width":"4"}),el("rect",{x:35,y:47,width:50,height:14,rx:2,fill:"none",stroke:"currentColor","stroke-width":"3"}));const t=el("text",{x:60,y:57,"text-anchor":"middle","font-size":"9","font-weight":"800",fill:"currentColor"});t.textContent=clasp;svg.append(t);return svg;}
function ribbon(pattern=[]){const svg=groupSvg("0 0 120 36");const colors=pattern.length?pattern:["#777"];const width=120/colors.length;colors.forEach((fill,index)=>svg.append(el("rect",{x:index*width,y:0,width:width+.2,height:36,fill})));svg.append(el("rect",{x:.8,y:.8,width:118.4,height:34.4,fill:"none",stroke:"rgba(255,255,255,.42)","stroke-width":"1.6"}));return svg;}
function tab(text="TAB"){const svg=groupSvg("0 0 120 36");svg.append(el("path",{d:"M10 25 Q60 4 110 25 L106 34 Q60 16 14 34 Z",fill:"#111",stroke:"currentColor","stroke-width":"2"}));const t=el("text",{x:60,y:26,"text-anchor":"middle","font-size":"14","font-weight":"900",fill:"#fff","letter-spacing":"2"});t.textContent=text;svg.append(t);return svg;}
export function createInsignia(definition,{qualificationResult=null,badgeClasp=null}={}){let svg;if(qualificationResult)svg=qualificationBadge(qualificationResult,badgeClasp??"RIFLE");else{const display=definition?.display??{};if(display.kind==="ribbon")svg=ribbon(display.ribbonPattern);else if(display.iconId==="badge_parachutist_basic")svg=badgeParachutist();else if(display.iconId==="badge_combat_infantry")svg=rifleWreath(true);else if(display.iconId==="badge_expert_infantry")svg=rifleWreath(false);else if(display.iconId==="badge_air_assault")svg=badgeAirAssault();else if(display.kind==="tab")svg=tab(display.text??definition.shortName??definition.name);else svg=groupSvg();}const wrapper=document.createElement("span");wrapper.className=`insignia insignia-${definition?.display?.kind??(qualificationResult?"badge":"unknown")}`;wrapper.append(svg);wrapper.title=definition?.name??`${qualificationResult} qualification`;return wrapper;}
