import { createEntityId } from "../core/ids.js";
import { commandResult } from "../core/commandResult.js";
import { advanceClock } from "../services/simulationClock.js";
import { simulatePersonnelLifecycle } from "../services/personnelLifecycle.js";
import { processPersonnelAdministration } from "../services/personnelAdministration.js";
import { applyEffects, ensureSkillProfile } from "../services/effectEngine.js";
import { resolveActivityEvent } from "../services/gameplayEvents.js";
import { recordAction, recordNotification } from "../services/recordServices.js";

export function performActivity(store, registries, personId, activityId) {
  const activity = registries.activities.get(activityId);
  const before = store.getState().entities.people[personId];
  if (!before) throw new Error(`Unknown person ${personId}.`);
  const rank = registries.ranks.get(before.affiliation.rankId);
  const eligibility = activity.eligibility ?? {};
  if (eligibility.allowedStatuses && !eligibility.allowedStatuses.includes(before.condition.status)) throw new Error(`${activity.name} is unavailable while status is ${before.condition.status}.`);
  if (before.condition.health < (eligibility.minimumHealth ?? 0)) throw new Error(`${activity.name} requires at least ${eligibility.minimumHealth}% health.`);
  if (eligibility.minimumRankLevel && rank.hierarchyLevel < eligibility.minimumRankLevel) throw new Error(`${activity.name} requires a higher rank.`);
  if (eligibility.requiresAssignedUnit && !before.affiliation.unitId) throw new Error(`${activity.name} requires a unit assignment.`);
  const notifications = [];
  const startDate = store.getState().world.date;
  const relationshipIds = [...(store.getIndexes().relationshipsByPersonId?.get(personId) ?? [])];
  const currentElapsedDay = store.getState().world.clock.elapsedDays;
  const recentSame = [...(store.getIndexes().activityRecordsByPersonId?.get(personId) ?? [])].map(id => store.getState().entities.activityRecords[id]).filter(r => r?.activityDefinitionId === activityId && currentElapsedDay - (r.endElapsedDay ?? -9999) <= 7).length;
  const repetitionMultiplier = recentSame >= 3 ? 0.4 : recentSame === 2 ? 0.6 : recentSame === 1 ? 0.8 : 1;
  let activityRecordId;
  store.mutate(draft => {
    const person = draft.entities.people[personId];
    const profile = ensureSkillProfile(draft, registries, personId);
    const unit = person.affiliation.unitId ? draft.entities.units[person.affiliation.unitId] : null;
    const snapshot = () => ({ experience: person.career.experience, prestige: person.career.prestige, health: person.condition.health, morale: person.condition.morale, readiness: person.condition.readiness, fatigue: person.condition.fatigue, skills: { ...profile.values }, unitReadiness: unit?.condition?.readiness ?? null, unitCohesion: unit?.condition?.cohesion ?? null });
    const beforeSnapshot = snapshot();
    advanceClock(draft, activity.durationDays);
    simulatePersonnelLifecycle(draft, activity.durationDays, registries, { excludePersonId: personId });
    processPersonnelAdministration(draft, registries);
    const scaledEffects = activity.effects.map(effect => ({ ...effect, value: Number(effect.value) > 0 && effect.target !== "person" || (Number(effect.value) > 0 && !String(effect.field ?? "").includes("fatigue")) ? Math.max(1, Math.round(Number(effect.value) * repetitionMultiplier)) : effect.value }));
    applyEffects(draft, registries, { personId, unitId: person.affiliation.unitId, relationshipIds, effects: scaledEffects });
    const event = resolveActivityEvent(draft, registries, { personId, unitId: person.affiliation.unitId, relationshipIds, activityId: activity.id, eventTableId: activity.eventTableId });
    if (event?.notificationId) notifications.push(event.notificationId);
    const afterSnapshot = snapshot();
    const deltas = {};
    for (const key of ["experience","prestige","health","morale","readiness","fatigue","unitReadiness","unitCohesion"]) if (beforeSnapshot[key] != null && afterSnapshot[key] !== beforeSnapshot[key]) deltas[key] = afterSnapshot[key] - beforeSnapshot[key];
    deltas.skills = Object.fromEntries(Object.keys(afterSnapshot.skills).filter(key => afterSnapshot.skills[key] !== beforeSnapshot.skills[key]).map(key => [key, afterSnapshot.skills[key] - beforeSnapshot.skills[key]]));
    const positive = Object.values(deltas.skills).reduce((a,b)=>a+b,0) + Math.max(0,deltas.readiness ?? 0) + Math.max(0,deltas.unitCohesion ?? 0);
    const negative = Math.max(0,-(deltas.health ?? 0)) + Math.max(0,deltas.fatigue ?? 0) / 4;
    const rating = positive >= 6 && negative < 2 ? "exceptional" : positive >= 3 && negative < 4 ? "strong" : negative >= 5 ? "poor" : "satisfactory";
    activityRecordId = createEntityId(draft, "activity");
    draft.entities.activityRecords[activityRecordId] = { id: activityRecordId, schemaVersion: 1, activityDefinitionId: activity.id, personId, unitId: person.affiliation.unitId, startDate, endDate: draft.world.date, durationDays: activity.durationDays, endElapsedDay: draft.world.clock.elapsedDays, repetitionMultiplier, status: "completed", eventRecordId: event?.eventRecordId ?? null, performanceRating: rating, before: beforeSnapshot, after: afterSnapshot, deltas };
    const perfId = createEntityId(draft, "perf");
    draft.entities.performanceRecords[perfId] = { id: perfId, schemaVersion: 1, personId, sourceType: "activity", sourceId: activityRecordId, gameDate: draft.world.date, rating, notes: `${activity.name} completed with ${rating} performance.`, deltas };
    const completionNoticeId = recordNotification(draft, { personId, type: "activity_completed", title: `${activity.name} Complete`, message: `${activity.name} completed after ${activity.durationDays} day${activity.durationDays === 1 ? "" : "s"}.`, priority: "normal", references: { activityRecordId } });
    notifications.unshift(completionNoticeId);
    recordAction(draft, { actorPersonId: personId, commandType: "perform_activity", payload: { activityId, durationDays: activity.durationDays }, resultCode: "activity_completed" });
  }, ["people", "history", "notifications", "actions", "admin", "career", "activities"]);
  return commandResult({ code: "activity_completed", message: `${activity.name} completed.`, data: { activityRecordId, activityId }, notifications });
}
